using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Remoting.Contexts;
using System.Text;
using System.Threading.Tasks;

namespace McFuncCompiler.Parser.NbtJson
{
    /// <summary>
    /// Converts an object (for example one generated by <see cref="NbtJsonParser"/>) into Minecraft's weird NBT JSON.
    /// </summary>
    public class NbtJsonCompiler
    {
        private object _nbt;

        NbtJsonCompiler(object nbt)
        {
            _nbt = nbt;
        }

        public string Compile(object nbt)
        {
            StringBuilder builder = new StringBuilder();
            


            return builder.ToString();
        }
    }
}
